LetExp([
 VarDec(str1,true,NONE,
  StringExp("abc")),
 VarDec(str2,true,NONE,
  StringExp("abd")),
 VarDec(str3,true,NONE,
  StringExp("abc"))],
 SeqExp[
  IfExp(
   IfExp(
    OpExp(EqOp,
     VarExp(
      SimpleVar(str1)),
     VarExp(
      SimpleVar(str2))),
    OpExp(EqOp,
     VarExp(
      SimpleVar(str1)),
     VarExp(
      SimpleVar(str3))),
    IntExp(0)),
   CallExp(print,[
    StringExp("same")]),
   CallExp(print,[
    StringExp("different")]))])
