LetExp([
 VarDec(a,true,NONE,
  IntExp(0)),
 VarDec(b,true,NONE,
  IntExp(1)),
 VarDec(c,true,NONE,
  IntExp(2)),
 VarDec(N,true,NONE,
  IntExp(10))],
 SeqExp[
  AssignExp(
   SimpleVar(b),
   OpExp(PlusOp,
    VarExp(
     SimpleVar(a)),
    IntExp(1))),
  AssignExp(
   SimpleVar(c),
   OpExp(PlusOp,
    VarExp(
     SimpleVar(c)),
    VarExp(
     SimpleVar(b)))),
  AssignExp(
   SimpleVar(a),
   OpExp(TimesOp,
    VarExp(
     SimpleVar(b)),
    IntExp(2))),
  VarExp(
   SimpleVar(N))])
