LetExp([
 VarDec(st,false,NONE,
  StringExp("abc")),
 TypeDec[
  (i,
   NameTy(int))],
 VarDec(a,false,SOME(i),
  IntExp(2)),
 FunctionDec[
  (nfactor,[
   (n,false,int),
   (m,false,string),
   (k,false,i)],
SOME(int),
   IfExp(
    OpExp(EqOp,
     VarExp(
      SimpleVar(n)),
     IntExp(0)),
    IntExp(1),
    OpExp(TimesOp,
     VarExp(
      SimpleVar(n)),
     CallExp(nfactor,[
      OpExp(MinusOp,
       VarExp(
        SimpleVar(n)),
       IntExp(1))]))))],
 VarDec(b,false,NONE,
  OpExp(PlusOp,
   VarExp(
    SimpleVar(a)),
   CallExp(nfactor,[
    VarExp(
     SimpleVar(a))])))],
 SeqExp[
  ForExp(
i,false,
   IntExp(10),
   IntExp(11),
   AssignExp(
    SimpleVar(i),
    OpExp(MinusOp,
     VarExp(
      SimpleVar(i)),
     IntExp(1)))),
  AssignExp(
   SimpleVar(st),
   StringExp("asd")),
  CallExp(nfactor,[
   IntExp(10),
   StringExp("a"),
   IntExp(10)])])
