LetExp([
 VarDec(st,false,NONE,
  StringExp("abc")),
 TypeDec[
  (i,
   NameTy(int))],
 VarDec(a,false,SOME(i),
  IntExp(2)),
 FunctionDec[
  (nfactor,[
   (n,false,int)],
SOME(int),
   IfExp(
    OpExp(EqOp,
     VarExp(
      SimpleVar(n)),
     IntExp(0)),
    IntExp(1),
    OpExp(TimesOp,
     VarExp(
      SimpleVar(n)),
     CallExp(nfactor,[
      OpExp(MinusOp,
       VarExp(
        SimpleVar(n)),
       IntExp(1))]))))],
 VarDec(b,false,NONE,
  OpExp(PlusOp,
   VarExp(
    SimpleVar(a)),
   CallExp(nfactor,[
    VarExp(
     SimpleVar(a))])))],
 SeqExp[
  AssignExp(
   SimpleVar(st),
   StringExp("bcd")),
  CallExp(nfactor,[
   IntExp(10)])])
