LetExp([
 TypeDec[
  (rectype,
   RecordTy[
    (name,false,string),
    (id,false,int)])],
 VarDec(rec1,false,NONE,
  RecordExp(rectype,[

   (name,
    StringExp("Name")),
   (id,
    IntExp(0))])),
 TypeDec[
  (list,
   RecordTy[
    (first,false,int),
    (rest,false,list)])],
 VarDec(st,false,NONE,
  StringExp("abc")),
 TypeDec[
  (i,
   NameTy(int))],
 VarDec(a,false,SOME(i),
  IntExp(2)),
 FunctionDec[
  (nfactor,[
   (n,false,int)],
SOME(int),
   IfExp(
    OpExp(EqOp,
     VarExp(
      SimpleVar(n)),
     IntExp(0)),
    IntExp(1),
    OpExp(TimesOp,
     VarExp(
      SimpleVar(n)),
     CallExp(nfactor,[
      OpExp(MinusOp,
       VarExp(
        SimpleVar(n)),
       IntExp(1))]))))],
 VarDec(b,false,NONE,
  OpExp(PlusOp,
   VarExp(
    SimpleVar(a)),
   CallExp(nfactor,[
    VarExp(
     SimpleVar(a))])))],
 SeqExp[
  AssignExp(
   FieldVar(
    SimpleVar(rec1),
    a),
   StringExp("asd")),
  ForExp(
i,false,
   IntExp(10),
   OpExp(MinusOp,
    IntExp(0),
    IntExp(1)),
   AssignExp(
    SimpleVar(i),
    OpExp(MinusOp,
     VarExp(
      SimpleVar(i)),
     IntExp(1)))),
  AssignExp(
   SimpleVar(st),
   StringExp("asd")),
  CallExp(nfactor,[
   IntExp(10)])])
